### ISSUE TITLE
[E_bains.m] Line 51: is the last input of mixed correction?

### ISSUE THREAD

**Issue by duochanatharvard** [ggebbie/OPT2k#6]
c_ind = mixit(d_ind,it,jt,kt,ones(Nfield,1));
Seems the last input should be "inmixlyr" for the function to return an indicator of wether in the mix-layer.

**Comment by duochanatharvard** [comment]
Nevermind, this function seems to find the weight for depth instead of only in the mixing layer.

**Comment by duochanatharvard** [comment]
Nevermind, this function seems to find the weight for depth instead of only in the mixing layer.

**Comment by ggebbie** [comment]
Right, the original code attempts to get the volume of the Indian Ocean. It knows the surface definition of the Indian, and then needs to identify all subsurface gridcells below that surface.
