### ISSUE TITLE
Missing modules and variables

### ISSUE THREAD

**Issue by duochanatharvard** [ggebbie/OPT2k#7]
Module "SSTfirstguess" is missing

Gchall in "OPTfirstguess" is not defined

**Comment by ggebbie** [comment]
`SSTfirstguess` now provided, `Gchall` defined in `SSTfirstguess`. Would it be better to have OPTfirstguess not depend on SSTfirstguess?

**Comment by duochanatharvard** [comment]
Wonderful!  I agree that the initial guess of boundary SSTs can be provided as a data file.  But let's keep "SSTfirstguess" here for now :-)
