### ISSUE TITLE
"CDF2(Nlag,:)  = CDF(end,:);" in Process_master_greens_functions

### ISSUE THREAD

**Issue by duochanatharvard** [ggebbie/OPT2k#8]
Why this line is needed?  Would it create large discontinuity at the end of 2000 years?

**Comment by ggebbie** [comment]
This line doesn't create a large discontinuity in practice because there is so little ocean response at lags of 2,000 years and beyond. The line is correct under the assumption that the surface boundary was fixed for all lags of 2,000 years and greater.

**Comment by duochanatharvard** [comment]
Thanks for the explanation.  In addition, I guess the results will not be much different with/without this line, because for a 2000 year simulation, linear-response-function with a 2000-year lag will only come into play for the forcing in the first time step.
